.TH "Répertoire de référence de model/geometry" 3 "Vendredi 24 Avril 2015" "Starlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de model/geometry \- 
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBellipse\&.hpp\fP"
.br
.ti -1c
.RI "fichier \fBline\&.hpp\fP"
.br
.ti -1c
.RI "fichier \fBpoint\&.hpp\fP"
.br
.ti -1c
.RI "fichier \fBrectangle\&.hpp\fP"
.br
.ti -1c
.RI "fichier \fButilities\&.hpp\fP"
.br
.in -1c
