.TH "model/elements/element.hpp" 3 "Vendredi 24 Avril 2015" "Starlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model/elements/element.hpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBElement\fP"
.br
.RI "\fIUn élément est un composant du jeu se devant de communiquer son état au niveau le gérant\&. \fP"
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Starlight à partir du code source\&.
