.TH "model/geometry/ellipse.hpp" 3 "Vendredi 24 Avril 2015" "Starlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model/geometry/ellipse.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <ostream>\fP
.br
\fC#include 'model/geometry/point\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEllipse\fP"
.br
.RI "\fIReprésente un cercle sous la forme; $ circle \equiv x^2/xRadius + y^2/yRadius = 1 $\&. \fP"
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &, const \fBEllipse\fP &)"
.br
.RI "\fIDéfinition, externe, de l'opérateur permettant de produire un affichage formaté\&. \fP"
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "std::ostream& operator<< (std::ostream &, const \fBEllipse\fP &)"

.PP
Définition, externe, de l'opérateur permettant de produire un affichage formaté\&. 
.PP
\fBRenvoie:\fP
.RS 4
Le ostream rempli de la chaine formatée représentant l'ellipse en paramètre\&. 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Starlight à partir du code source\&.
