.TH "view/windows/levelview.hpp" 3 "Vendredi 24 Avril 2015" "Starlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
view/windows/levelview.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QGraphicsView>\fP
.br
\fC#include <QWidget>\fP
.br
\fC#include <QGraphicsLineItem>\fP
.br
\fC#include <QGraphicsScene>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLevelView\fP"
.br
.RI "\fICette classe représente le niveau qui va être joué lors d'une partie\&. \fP"
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Starlight à partir du code source\&.
