.TH "LevelView" 3 "Vendredi 24 Avril 2015" "Starlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LevelView \- Cette classe représente le niveau qui va être joué lors d'une partie\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <levelview\&.hpp>\fP
.SS "Connecteurs publics"

.in +1c
.ti -1c
.RI "void \fBsetLevelFilePath\fP (const QString)"
.br
.RI "\fIPermet de changer le fichier de niveau et d'afficher ce niveau\&. \fP"
.ti -1c
.RI "void \fBloadLevelFromFile\fP ()"
.br
.RI "\fIPermet d'afficher le fichier niveau dont la vue courante contient le chemin en attribut\&. \fP"
.ti -1c
.RI "void \fBupdateDisplay\fP ()"
.br
.RI "\fIPermet de rafraichir l'affichage lorsque le niveau change d'état\&. \fP"
.ti -1c
.RI "void \fBdisplayEndOfGame\fP ()"
.br
.RI "\fIPermet d'afficher une boite de dialogue informant l'utilisateur de la fin du jeu\&. \fP"
.in -1c
.SS "Signaux"

.in +1c
.ti -1c
.RI "void \fBdisplayingStarted\fP ()"
.br
.RI "\fISignale que le niveau doit être affiché\&. \fP"
.ti -1c
.RI "void \fBdisplayingStopped\fP ()"
.br
.RI "\fISignale que le niveau ne doit plus être affiché\&. \fP"
.in -1c
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBLevelView\fP (QWidget *=0)"
.br
.RI "\fIPermet de créer une vue du niveau\&. \fP"
.ti -1c
.RI "\fB~LevelView\fP ()"
.br
.in -1c
.SS "Fonctions membres privées"

.in +1c
.ti -1c
.RI "void \fBupdateRays\fP ()"
.br
.RI "\fIPermet de mettre à jour l'affichage des rayons\&. \fP"
.in -1c
.SS "Attributs privés"

.in +1c
.ti -1c
.RI "QGraphicsScene * \fBscene\fP"
.br
.RI "\fILa scène qui comportera l'ensemble des éléments graphiques de la partie\&. \fP"
.ti -1c
.RI "\fBLevel\fP * \fBlevel\fP"
.br
.RI "\fILe niveau quel la vue observe\&. \fP"
.ti -1c
.RI "std::string \fBdisplayedLevelFilePath\fP"
.br
.RI "\fILe chemin du fichier chargé par l'utilisateur\&. \fP"
.ti -1c
.RI "std::vector< QGraphicsLineItem * > \fBrays\fP"
.br
.RI "\fIL'ensemble des rayons dessinés\&. \fP"
.ti -1c
.RI "std::vector< \fBMirrorView\fP * > \fBmirrors\fP"
.br
.RI "\fIL'ensemble des miroirs dessinés\&. \fP"
.in -1c
.SH "Description détaillée"
.PP 
Cette classe représente le niveau qui va être joué lors d'une partie\&. 
.PP
Définition à la ligne 18 du fichier levelview\&.hpp\&.
.PP
Est dérivée de QGraphicsView\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "LevelView::LevelView (QWidget * = \fC0\fP)\fC [explicit]\fP"

.PP
Permet de créer une vue du niveau\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIparent\fP L'objet graphique parent\&. 
.RE
.PP

.SS "LevelView::~LevelView ()"

.SH "Documentation des fonctions membres"
.PP 
.SS "void LevelView::displayEndOfGame ()\fC [slot]\fP"

.PP
Permet d'afficher une boite de dialogue informant l'utilisateur de la fin du jeu\&. 
.SS "void LevelView::displayingStarted ()\fC [signal]\fP"

.PP
Signale que le niveau doit être affiché\&. 
.SS "void LevelView::displayingStopped ()\fC [signal]\fP"

.PP
Signale que le niveau ne doit plus être affiché\&. 
.SS "void LevelView::loadLevelFromFile ()\fC [slot]\fP"

.PP
Permet d'afficher le fichier niveau dont la vue courante contient le chemin en attribut\&. 
.SS "void LevelView::setLevelFilePath (const QString)\fC [slot]\fP"

.PP
Permet de changer le fichier de niveau et d'afficher ce niveau\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIlevelFile\fP chemin vers le fichier du nouveau niveau à afficher\&. 
.RE
.PP

.SS "void LevelView::updateDisplay ()\fC [slot]\fP"

.PP
Permet de rafraichir l'affichage lorsque le niveau change d'état\&. 
.SS "void LevelView::updateRays ()\fC [private]\fP"

.PP
Permet de mettre à jour l'affichage des rayons\&. 
.SH "Documentation des données membres"
.PP 
.SS "std::string LevelView::displayedLevelFilePath\fC [private]\fP"

.PP
Le chemin du fichier chargé par l'utilisateur\&. 
.PP
Définition à la ligne 36 du fichier levelview\&.hpp\&.
.SS "\fBLevel\fP* LevelView::level\fC [private]\fP"

.PP
Le niveau quel la vue observe\&. 
.PP
Définition à la ligne 31 du fichier levelview\&.hpp\&.
.SS "std::vector<\fBMirrorView\fP *> LevelView::mirrors\fC [private]\fP"

.PP
L'ensemble des miroirs dessinés\&. 
.PP
Définition à la ligne 46 du fichier levelview\&.hpp\&.
.SS "std::vector<QGraphicsLineItem *> LevelView::rays\fC [private]\fP"

.PP
L'ensemble des rayons dessinés\&. 
.PP
Définition à la ligne 41 du fichier levelview\&.hpp\&.
.SS "QGraphicsScene* LevelView::scene\fC [private]\fP"

.PP
La scène qui comportera l'ensemble des éléments graphiques de la partie\&. 
.PP
Définition à la ligne 26 du fichier levelview\&.hpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Starlight à partir du code source\&.
