.TH "model/elements/level.hpp" 3 "Vendredi 24 Avril 2015" "Starlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model/elements/level.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'model/exception/starlightexception\&.hpp'\fP
.br
\fC#include 'model/elements/wall\&.hpp'\fP
.br
\fC#include 'model/elements/mirror\&.hpp'\fP
.br
\fC#include 'model/elements/crystal\&.hpp'\fP
.br
\fC#include 'model/elements/lens\&.hpp'\fP
.br
\fC#include 'model/elements/nuke\&.hpp'\fP
.br
\fC#include 'model/elements/source\&.hpp'\fP
.br
\fC#include 'model/elements/dest\&.hpp'\fP
.br
\fC#include 'model/elements/ray\&.hpp'\fP
.br
\fC#include 'view/windows/levelview\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLevel\fP"
.br
.RI "\fIModélise une carte telle qu'utilisée dans le jeu\&. \fP"
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Starlight à partir du code source\&.
