.TH "model/geometry/line.hpp" 3 "Vendredi 24 Avril 2015" "Starlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model/geometry/line.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include <ostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLine\fP"
.br
.RI "\fIReprésente une droite sous la forme de son équation complète; $ eq \equiv y = slope \cdot x + indepTerm $\&. \fP"
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &, const \fBLine\fP &)"
.br
.RI "\fIDéfinition, externe, de l'opérateur permettant de produire un affichage formaté\&. \fP"
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "std::ostream& operator<< (std::ostream &, const \fBLine\fP &)"

.PP
Définition, externe, de l'opérateur permettant de produire un affichage formaté\&. 
.PP
\fBRenvoie:\fP
.RS 4
Le ostream rempli de la chaine formatée représentant la Ligne en paramètre\&. 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Starlight à partir du code source\&.
