.TH "MainMenu" 3 "Vendredi 24 Avril 2015" "Starlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainMenu \- Cette classe représente le menu principal du jeu permettant de\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mainmenu\&.hpp>\fP
.SS "Connecteurs publics"

.in +1c
.ti -1c
.RI "void \fBselectNewLevelFile\fP ()"
.br
.RI "\fIPermet de faire sélectionner un fichier de niveau par l'utilisateur\&. \fP"
.ti -1c
.RI "void \fBdisplayRules\fP ()"
.br
.RI "\fIPermet d'afficher une fenêtre de dialogue contenant les règles et les commandes du jeu\&. \fP"
.in -1c
.SS "Signaux"

.in +1c
.ti -1c
.RI "void \fBnewLevelFileSelected\fP (const QString)"
.br
.RI "\fISignale qu'un nouveau fichier a été sélectionné par l'utilisateur\&. \fP"
.in -1c
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBMainMenu\fP (QWidget *=0)"
.br
.RI "\fIPermet de créer un menu du jeu\&. \fP"
.ti -1c
.RI "\fB~MainMenu\fP ()"
.br
.in -1c
.SS "Fonctions membres privées"

.in +1c
.ti -1c
.RI "QLabel * \fBsetLogo\fP ()"
.br
.in -1c
.SH "Description détaillée"
.PP 
Cette classe représente le menu principal du jeu permettant de\&. 


.PD 0

.IP "\(bu" 2
sélectionner un niveau à jouer,  
.IP "\(bu" 2
lire les règles du jeu,  
.IP "\(bu" 2
quitter le jeu\&.  
.PP

.PP
Définition à la ligne 15 du fichier mainmenu\&.hpp\&.
.PP
Est dérivée de QFrame\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "MainMenu::MainMenu (QWidget * = \fC0\fP)\fC [explicit]\fP"

.PP
Permet de créer un menu du jeu\&. 
.SS "MainMenu::~MainMenu ()"

.SH "Documentation des fonctions membres"
.PP 
.SS "void MainMenu::displayRules ()\fC [slot]\fP"

.PP
Permet d'afficher une fenêtre de dialogue contenant les règles et les commandes du jeu\&. 
.SS "void MainMenu::newLevelFileSelected (const QString)\fC [signal]\fP"

.PP
Signale qu'un nouveau fichier a été sélectionné par l'utilisateur\&. 
.PP
\fBParamètres:\fP
.RS 4
\fInewLevelFile\fP Chemin vers le nouveau fichier sélectionné\&. 
.RE
.PP

.SS "void MainMenu::selectNewLevelFile ()\fC [slot]\fP"

.PP
Permet de faire sélectionner un fichier de niveau par l'utilisateur\&. 
.PP
\fBParamètres:\fP
.RS 4
\fInewLevelFile\fP Chemin vers le nouveau fichier sélectionné\&. 
.RE
.PP

.SS "QLabel* MainMenu::setLogo ()\fC [private]\fP"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Starlight à partir du code source\&.
