.TH "view/windows/mainwindow.hpp" 3 "Vendredi 24 Avril 2015" "Starlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
view/windows/mainwindow.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QMenu>\fP
.br
\fC#include <QMenuBar>\fP
.br
\fC#include <QMainWindow>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.RI "\fICette classe est la fenêtre principale du jeu qui englobe toutes les autres vues\&. \fP"
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Starlight à partir du code source\&.
