.TH "view/windows/mainmenu.hpp" 3 "Vendredi 24 Avril 2015" "Starlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
view/windows/mainmenu.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QLabel>\fP
.br
\fC#include <QFrame>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainMenu\fP"
.br
.RI "\fICette classe représente le menu principal du jeu permettant de\&. \fP"
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Starlight à partir du code source\&.
