.TH "view/dynamicElements/mirrorview.hpp" 3 "Vendredi 24 Avril 2015" "Starlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
view/dynamicElements/mirrorview.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QGraphicsLineItem>\fP
.br
\fC#include <QKeyEvent>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMirrorView\fP"
.br
.RI "\fICette classe représente graphiquement un miroir du jeu permettant d'interagir avec lui à l'aide de la souris et du clavier\&. \fP"
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Starlight à partir du code source\&.
