.TH "model/elements/nuke.hpp" 3 "Vendredi 24 Avril 2015" "Starlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model/elements/nuke.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ostream>\fP
.br
\fC#include 'model/elements/element\&.hpp'\fP
.br
\fC#include 'model/geometry/ellipse\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNuke\fP"
.br
.RI "\fICette classe modélise les bombes utilisées dans le jeu\&. \fP"
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &, const \fBNuke\fP &)"
.br
.RI "\fIDéfinition, externe, de l'opérateur permettant de produire un affichage formaté\&. \fP"
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "std::ostream& operator<< (std::ostream &, const \fBNuke\fP &)"

.PP
Définition, externe, de l'opérateur permettant de produire un affichage formaté\&. 
.PP
\fBRenvoie:\fP
.RS 4
Le ostream rempli de la chaine formatée représentant le \fBNuke\fP en paramètre\&. 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Starlight à partir du code source\&.
