.TH "model/geometry/point.hpp" 3 "Vendredi 24 Avril 2015" "Starlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model/geometry/point.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPoint\fP"
.br
.RI "\fICette classe modélise un point de coordonnés dans le plan $ R^2 $ sous deux formes : \fP"
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &, const \fBPoint\fP &)"
.br
.RI "\fIDéfinition, externe, de l'opérateur permettant de produire un affichage formaté\&. \fP"
.in -1c
.SH "Documentation des fonctions"
.PP 
.SS "std::ostream& operator<< (std::ostream &, const \fBPoint\fP &)"

.PP
Définition, externe, de l'opérateur permettant de produire un affichage formaté\&. 
.PP
\fBRenvoie:\fP
.RS 4
Le ostream rempli de la chaine formatée représentant le \fBPoint\fP en paramètre\&. 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Starlight à partir du code source\&.
