.TH "SourceView" 3 "Vendredi 24 Avril 2015" "Starlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceView \- Cette classe permet de représenter graphiquement une source, lui permettant de communiquer les actions utilisateurs\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sourceview\&.hpp>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBSourceView\fP (\fBSource\fP *)"
.br
.RI "\fIPermet de créer une vue liée à une source\&. \fP"
.ti -1c
.RI "\fB~SourceView\fP ()"
.br
.in -1c
.SS "Fonctions membres protégées"

.in +1c
.ti -1c
.RI "void \fBmousePressEvent\fP (QGraphicsSceneMouseEvent *)"
.br
.RI "\fIPermet de réagir sur le modèle lors d'un 'input user'\&. \fP"
.in -1c
.SS "Attributs privés"

.in +1c
.ti -1c
.RI "\fBSource\fP * \fBsource\fP"
.br
.RI "\fILa source représentée par cette vue\&. \fP"
.ti -1c
.RI "QPen \fBpen\fP"
.br
.RI "\fILes paramètres visuels du trait de la source\&. \fP"
.ti -1c
.RI "QBrush \fBbrush\fP"
.br
.RI "\fILes paramètres visuels du plein de la source\&. \fP"
.in -1c
.SH "Description détaillée"
.PP 
Cette classe permet de représenter graphiquement une source, lui permettant de communiquer les actions utilisateurs\&. 
.PP
Définition à la ligne 14 du fichier sourceview\&.hpp\&.
.PP
Est dérivée de QGraphicsRectItem\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "SourceView::SourceView (\fBSource\fP *)"

.PP
Permet de créer une vue liée à une source\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIsource\fP La source liée à cette vue\&. 
.RE
.PP

.SS "SourceView::~SourceView ()"

.SH "Documentation des fonctions membres"
.PP 
.SS "void SourceView::mousePressEvent (QGraphicsSceneMouseEvent *)\fC [protected]\fP"

.PP
Permet de réagir sur le modèle lors d'un 'input user'\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIevent\fP Un évènement 'input user'\&. 
.RE
.PP

.SH "Documentation des données membres"
.PP 
.SS "QBrush SourceView::brush\fC [private]\fP"

.PP
Les paramètres visuels du plein de la source\&. 
.PP
Définition à la ligne 29 du fichier sourceview\&.hpp\&.
.SS "QPen SourceView::pen\fC [private]\fP"

.PP
Les paramètres visuels du trait de la source\&. 
.PP
Définition à la ligne 24 du fichier sourceview\&.hpp\&.
.SS "\fBSource\fP* SourceView::source\fC [private]\fP"

.PP
La source représentée par cette vue\&. 
.PP
Définition à la ligne 19 du fichier sourceview\&.hpp\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Starlight à partir du code source\&.
