.TH "view/dynamicElements/sourceview.hpp" 3 "Vendredi 24 Avril 2015" "Starlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
view/dynamicElements/sourceview.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QGraphicsRectItem>\fP
.br
\fC#include <QPen>\fP
.br
\fC#include <QBrush>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSourceView\fP"
.br
.RI "\fICette classe permet de représenter graphiquement une source, lui permettant de communiquer les actions utilisateurs\&. \fP"
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Starlight à partir du code source\&.
