.TH "StarlightException" 3 "Vendredi 24 Avril 2015" "Starlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StarlightException \- Cette classe représente une exception spécifique au jeu Starlight\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <starlightexception\&.hpp>\fP
.SS "Fonctions membres publiques"

.in +1c
.ti -1c
.RI "\fBStarlightException\fP (std::string)"
.br
.RI "\fIConstruit une nouvelle erreur inhérente au jeu\&. \fP"
.ti -1c
.RI "std::string \fBgetMessage\fP () const "
.br
.RI "\fIPermet d'obtenir le message d'erreur de l'exception\&. \fP"
.ti -1c
.RI "const char * \fBwhat\fP () const   throw ()"
.br
.RI "\fIPermet d'afficher l'erreur en cas d'erreur\&. \fP"
.in -1c
.SS "Attributs privés"

.in +1c
.ti -1c
.RI "std::string \fBerrorMsg\fP"
.br
.RI "\fILe message d'erreur de l'exception lancée\&. \fP"
.in -1c
.SH "Description détaillée"
.PP 
Cette classe représente une exception spécifique au jeu Starlight\&. 
.PP
Définition à la ligne 10 du fichier starlightexception\&.hpp\&.
.PP
Est dérivée de exception\&.
.SH "Documentation des constructeurs et destructeur"
.PP 
.SS "StarlightException::StarlightException (std::string)"

.PP
Construit une nouvelle erreur inhérente au jeu\&. 
.PP
\fBParamètres:\fP
.RS 4
\fIerrorMsg\fP Message expliquant l'erreur\&. 
.RE
.PP

.SH "Documentation des fonctions membres"
.PP 
.SS "std::string StarlightException::getMessage () const\fC [inline]\fP"

.PP
Permet d'obtenir le message d'erreur de l'exception\&. 
.PP
\fBRenvoie:\fP
.RS 4
Le message d'erreur de l'exception\&. 
.RE
.PP

.PP
Définition à la ligne 45 du fichier starlightexception\&.hpp\&.
.PP
Références errorMsg\&.
.PP
.nf
46 {
47     return this->errorMsg;
48 }
.fi
.SS "const char * StarlightException::what () const\fC [inline]\fP"

.PP
Permet d'afficher l'erreur en cas d'erreur\&. 
.PP
\fBRenvoie:\fP
.RS 4
Le message d'erreur\&. 
.RE
.PP

.PP
Définition à la ligne 50 du fichier starlightexception\&.hpp\&.
.PP
.nf
51 {
52     return this->errorMsg\&.c_str();
53 }
.fi
.SH "Documentation des données membres"
.PP 
.SS "std::string StarlightException::errorMsg\fC [private]\fP"

.PP
Le message d'erreur de l'exception lancée\&. 
.PP
Définition à la ligne 18 du fichier starlightexception\&.hpp\&.
.PP
Référencé par getMessage()\&.

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Starlight à partir du code source\&.
