.TH "model/exception/starlightexception.hpp" 3 "Vendredi 24 Avril 2015" "Starlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
model/exception/starlightexception.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <exception>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStarlightException\fP"
.br
.RI "\fICette classe représente une exception spécifique au jeu Starlight\&. \fP"
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Starlight à partir du code source\&.
