.TH "view/viewutilities.hpp" 3 "Vendredi 24 Avril 2015" "Starlight" \" -*- nroff -*-
.ad l
.nh
.SH NAME
view/viewutilities.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QGraphicsScene>\fP
.br
\fC#include <QGraphicsRectItem>\fP
.br
\fC#include <QGraphicsLineItem>\fP
.br
\fC#include <QGraphicsEllipseItem>\fP
.br
\fC#include <QColor>\fP
.br
\fC#include <QPointF>\fP
.br
\fC#include <QRectF>\fP
.br
\fC#include <QString>\fP
.br

.SS "Espaces de nommage"

.in +1c
.ti -1c
.RI " \fBviewUtilities\fP"
.br
.RI "\fIDivers fonctions utilitaires nécessaires aux vues\&. \fP"
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "QPointF \fBviewUtilities::toQPoint\fP (const \fBPoint\fP &)"
.br
.RI "\fIPermet de transformer un point en QPointF\&. \fP"
.ti -1c
.RI "QRectF \fBviewUtilities::toQRectF\fP (const \fBRectangle\fP &)"
.br
.RI "\fIPermet de transformer un rectangle en QRectF\&. \fP"
.ti -1c
.RI "QRectF \fBviewUtilities::toQRectF\fP (const \fBEllipse\fP &)"
.br
.RI "\fIPermet de représenter une ellipse, à partir du rectangle qui lui est circonscrit, en un QRectF\&. \fP"
.ti -1c
.RI "QGraphicsLineItem * \fBviewUtilities::getLine\fP (const \fBPoint\fP &, const \fBPoint\fP &, const QColor &, const int)"
.br
.RI "\fIPermet de générer une QGraphicsLine à partir des deux points délimitant un segment de droite\&. \fP"
.ti -1c
.RI "QGraphicsRectItem * \fBviewUtilities::getRect\fP (const \fBRectangle\fP &, const QColor &, const int)"
.br
.RI "\fIPermet de générer un QGraphicsRectItem représentant le rectangle passé en paramètre\&. \fP"
.ti -1c
.RI "QGraphicsEllipseItem * \fBviewUtilities::getEllipse\fP (const \fBEllipse\fP &, const QColor &, const int)"
.br
.RI "\fIPermet de générer un QGraphicsEllipseItem représentant l'ellipse passée en paramètre\&. \fP"
.ti -1c
.RI "QColor \fBviewUtilities::waveLengthToColor\fP (const \fBRay\fP &, const double=0\&.8)"
.br
.RI "\fIPermet de créé une QColor au format RGB selon la longueur d'onde passée en paramètre\&. \fP"
.ti -1c
.RI "QString * \fBviewUtilities::fileToQString\fP (const QString &)"
.br
.RI "\fIPermet de lire un fichier et de retourner son contenu en tant que QString\&. \fP"
.in -1c
.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Starlight à partir du code source\&.
